services:
  prometheus:
    image: prom/prometheus:latest
    container_name: triggerx-prometheus
    network_mode: "host"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.listen-address=0.0.0.0:${PROMETHEUS_PORT}'
    environment:
      - OPERATOR_ADDRESS=${OPERATOR_ADDRESS}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: triggerx-grafana
    network_mode: "host"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=triggerx
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SERVER_HTTP_PORT=${GRAFANA_PORT}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data: